use_frameworks!

platform :ios, '8.0'

target 'FCDecorationCollectionViewFlowLayoutOC_Example' do
  pod 'FCDecorationCollectionViewFlowLayoutOC', :path => '../'

  target 'FCDecorationCollectionViewFlowLayoutOC_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
